"""empty message

Revision ID: 30bec40af061
Revises: 91729da996fd
Create Date: 2026-06-12 00:55:03.892502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bec40af061'
down_revision = '91729da996fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('revision_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=200), nullable=True),
    sa.Column('meta_keywords', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pages', sa.Column('template', sa.String(length=200), nullable=True))
    op.add_column('pages', sa.Column('meta_description', sa.String(length=200), nullable=True))
    op.add_column('pages', sa.Column('meta_keywords', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('min_stock', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('cashier_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('discount_type', sa.String(length=10), nullable=True))
    op.add_column('transactions', sa.Column('discount_value', sa.Numeric(10, 2), nullable=True))
    op.drop_column('transactions', 'chashier_id')
    op.drop_index('ix_user_tokens_token_hash', table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_token_hash'), 'user_tokens', ['token_hash'], unique=True)
    op.drop_column('user_tokens', 'token_salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('token_salt', sa.VARCHAR(length=64), nullable=False))
    op.drop_index(op.f('ix_user_tokens_token_hash'), table_name='user_tokens')
    op.create_index('ix_user_tokens_token_hash', 'user_tokens', ['token_hash'], unique=False)
    op.add_column('transactions', sa.Column('chashier_id', sa.INTEGER(), nullable=True))
    op.drop_column('transactions', 'discount_value')
    op.drop_column('transactions', 'discount_type')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'cashier_id')
    op.drop_column('product', 'min_stock')
    op.drop_column('pages', 'meta_keywords')
    op.drop_column('pages', 'meta_description')
    op.drop_column('pages', 'template')
    op.drop_table('page_revisions')
    # ### end Alembic commands ###
