"""add cost_price, bundle_components

Revision ID: 454dbacafd84
Revises: 976eee7b20f9
Create Date: 2026-06-12 01:43:52.508371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454dbacafd84'
down_revision = '976eee7b20f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cost_price')
    op.drop_table('bundle_components')
    # ### end Alembic commands ###
