"""rename to shopyo_ecommerce_ prefix

Revision ID: 54f23b014f49
Revises: 1c6f25e61a59
Create Date: 2026-06-17 00:28:58.593741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f23b014f49'
down_revision = '1c6f25e61a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopyo_ecommerce_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopyo_ecommerce_customer_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopyo_ecommerce_locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('logged_in_customer_email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('payment_option_name', sa.String(length=120), nullable=True),
    sa.Column('payment_option_text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_vendors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_billing_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('town_city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('order_notes', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shopyo_ecommerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=300), nullable=True),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shopyo_ecommerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('last_purchase', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['shopyo_ecommerce_customer_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_deliveryoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shopyo_ecommerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_inventory_counts',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_order_items',
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shopyo_ecommerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_paymentoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shopyo_ecommerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_purchase_orders',
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['shopyo_ecommerce_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('starting_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_stock_transfers',
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['shopyo_ecommerce_locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['shopyo_ecommerce_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_subcategories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['shopyo_ecommerce_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('method_of_payment', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('discount_type', sa.String(length=10), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['shopyo_ecommerce_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_product',
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('in_stock', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discontinued', sa.Boolean(), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_onsale', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['shopyo_ecommerce_subcategories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['shopyo_ecommerce_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_purchase_order_items',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_barcode', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('quantity_received', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['shopyo_ecommerce_purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_barcode', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['shopyo_ecommerce_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_bundle_components',
    sa.Column('bundle_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_color',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_inventory_count_items',
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['shopyo_ecommerce_inventory_counts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_quick_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopyo_ecommerce_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['shopyo_ecommerce_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_size',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_stock_adjustments',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_stock_per_location',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['shopyo_ecommerce_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopyo_ecommerce_stock_transfer_items',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shopyo_ecommerce_product.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['shopyo_ecommerce_stock_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    op.drop_table('color')
    op.drop_table('coupons')
    op.drop_table('purchase_order_items')
    op.drop_table('bundle_components')
    op.drop_table('customer')
    op.drop_table('subcategories')
    op.drop_table('inventory_count_items')
    op.drop_table('transaction_items')
    op.drop_table('locations')
    op.drop_table('inventory_counts')
    op.drop_table('billing_details')
    op.drop_table('deliveryoptions')
    op.drop_table('transactions')
    op.drop_table('paymentoptions')
    op.drop_table('size')
    op.drop_table('stock_adjustments')
    op.drop_table('shifts')
    op.drop_table('categories')
    op.drop_table('resources')
    op.drop_table('stock_transfers')
    op.drop_table('quick_keys')
    op.drop_table('stock_transfer_items')
    op.drop_table('purchase_orders')
    op.drop_table('vendors')
    op.drop_table('images')
    op.drop_table('stock_per_location')
    op.drop_table('customer_groups')
    op.drop_table('order_items')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('in_stock', sa.INTEGER(), nullable=True),
    sa.Column('discontinued', sa.BOOLEAN(), nullable=True),
    sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('is_onsale', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('subcategory_id', sa.INTEGER(), nullable=False),
    sa.Column('min_stock', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_product_vendor_id')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=100), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_per_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=50), nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=50), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('file_width', sa.INTEGER(), nullable=False),
    sa.Column('file_height', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_location_id', sa.INTEGER(), nullable=False),
    sa.Column('to_location_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('subcategory_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('starting_cash', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('actual_cash', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('variance_cash', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_change', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymentoptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('text', sa.VARCHAR(length=300), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('method_of_payment', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cashier_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_transactions_location_id')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveryoptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('option', sa.VARCHAR(length=300), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), nullable=True),
    sa.Column('town_city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_notes', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_counts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('product_barcode', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_count_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('count_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('expected_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_qty', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['inventory_counts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_spent', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('order_count', sa.INTEGER(), nullable=True),
    sa.Column('last_purchase', sa.DATETIME(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle_components',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bundle_product_id', sa.INTEGER(), nullable=False),
    sa.Column('component_product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_barcode', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quantity_ordered', sa.INTEGER(), nullable=True),
    sa.Column('quantity_received', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('string', sa.VARCHAR(length=300), nullable=True),
    sa.Column('type', sa.VARCHAR(length=300), nullable=True),
    sa.Column('value', sa.VARCHAR(length=300), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('logged_in_customer_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('payment_option_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('payment_option_text', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shopyo_ecommerce_stock_transfer_items')
    op.drop_table('shopyo_ecommerce_stock_per_location')
    op.drop_table('shopyo_ecommerce_stock_adjustments')
    op.drop_table('shopyo_ecommerce_size')
    op.drop_table('shopyo_ecommerce_resources')
    op.drop_table('shopyo_ecommerce_quick_keys')
    op.drop_table('shopyo_ecommerce_inventory_count_items')
    op.drop_table('shopyo_ecommerce_color')
    op.drop_table('shopyo_ecommerce_bundle_components')
    op.drop_table('shopyo_ecommerce_transaction_items')
    op.drop_table('shopyo_ecommerce_purchase_order_items')
    op.drop_table('shopyo_ecommerce_product')
    op.drop_table('shopyo_ecommerce_transactions')
    op.drop_table('shopyo_ecommerce_subcategories')
    op.drop_table('shopyo_ecommerce_stock_transfers')
    op.drop_table('shopyo_ecommerce_shifts')
    op.drop_table('shopyo_ecommerce_purchase_orders')
    op.drop_table('shopyo_ecommerce_paymentoptions')
    op.drop_table('shopyo_ecommerce_order_items')
    op.drop_table('shopyo_ecommerce_inventory_counts')
    op.drop_table('shopyo_ecommerce_deliveryoptions')
    op.drop_table('shopyo_ecommerce_customer')
    op.drop_table('shopyo_ecommerce_coupons')
    op.drop_table('shopyo_ecommerce_billing_details')
    op.drop_table('shopyo_ecommerce_vendors')
    op.drop_table('shopyo_ecommerce_orders')
    op.drop_table('shopyo_ecommerce_locations')
    op.drop_table('shopyo_ecommerce_customer_groups')
    op.drop_table('shopyo_ecommerce_categories')
    # ### end Alembic commands ###
