"""add card fields to transactions

Revision ID: 69436821702c
Revises: 54f23b014f49
Create Date: 2026-06-17 23:48:51.170156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69436821702c'
down_revision = '54f23b014f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopyo_ecommerce_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_last_four', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_auth_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopyo_ecommerce_transactions', schema=None) as batch_op:
        batch_op.drop_column('card_auth_code')
        batch_op.drop_column('card_last_four')

    # ### end Alembic commands ###
